### ISSUE TITLE
设置文件hosts一栏无法为网站添加多个IP地址

### ISSUE THREAD

**Issue by mraandtux** [URenko/Accesser#119]
原标题：**Ubuntu 23.04出现tomllib.TOMLDecodeError: Cannot overwrite a value错误**

今天刚装上了Ubuntu 23.04，使用最新的Python 3.11安装Accesser 0.8.1，但出现下列错误：

```Traceback (most recent call last):
  File "/home/user/.local/bin/accesser", line 5, in <module>
    from accesser import run
  File "/home/user/.local/lib/python3.11/site-packages/accesser/__init__.py", line 33, in <module>
    from .utils import certmanager as cm
  File "/home/user/.local/lib/python3.11/site-packages/accesser/utils/certmanager.py", line 25, in <module>
    from . import setting
  File "/home/user/.local/lib/python3.11/site-packages/accesser/utils/setting.py", line 14, in <module>
    config = tomllib.load(f)
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tomllib/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tomllib/_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
tomllib.TOMLDecodeError: Cannot overwrite a value (at line 90, column 36)
```

注：已安装python3-toml, python3-tomlkit, python3-tomli, python3-tomli-w等包。

**Comment by URenko** [comment]
是否有修改过config.toml？

**Comment by mraandtux** [comment]
**后续**

config.toml不支持下列写法：
```
"（网址）" = "（IP地址）"
"（网址）" = "（另一个IP）"
```

当修改为`"（网址）" = "（IP地址1, IP地址2等）"`的时候就可以，搭配DNSCrypt的DoH也可以解析；但DNS解析完了就出现以下错误：

```
ERROR    asyncio: Task exception was never retrieved
future: <Task finished name='Task-99' coro=<handle() done, defined at /home/user/.local/lib/python3.11/site-packages/accesser/__init__.py:93> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/accesser/__init__.py", line 120, in handle
    await update_cert(host)
  File "/home/user/.local/lib/python3.11/site-packages/accesser/__init__.py", line 51, in update_cert
    cm.create_certificate(server_name)
  File "/home/user/.local/lib/python3.11/site-packages/accesser/utils/certmanager.py", line 84, in create_certificate
    rootpem = open(os.path.join(certpath ,"root.crt"), "rb").read()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'CERT/root.crt'
```

**Comment by URenko** [comment]
是的，内置DNS并不支持给一个域名指派多个IP地址，如需要可搭配DNSCrypt这样的专用程序食用。

关于证书路径的问题，我估计你将importca置否了，我看了下这里有点bug。
