### ISSUE TITLE
似乎从前两天开始e站里站就连不上了

### ISSUE THREAD

**Issue by wintermanxp** [URenko/Accesser#125]
错误日志如下

2023-05-18 16:06:42 DEBUG    Accesser: 127.0.0.1:14143 say: CONNECT exhentai.org:443 HTTP/1.1
2023-05-18 16:06:42 DEBUG    Accesser: [14143] DNS: exhentai.org -> 172.64.169.3
2023-05-18 16:06:42 DEBUG    Accesser: [14143] server_hostname=''
2023-05-18 16:06:42 ERROR    asyncio: Task was destroyed but it is pending!
task: <Task pending name='Task-393' coro=<handle() done, defined at accesser\__init__.py:93> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>>
2023-05-18 16:06:42 ERROR    asyncio: Task was destroyed but it is pending!
task: <Task pending name='Task-397' coro=<handle() done, defined at accesser\__init__.py:93> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>>
2023-05-18 16:06:42 ERROR    asyncio: Task was destroyed but it is pending!
task: <Task pending name='Task-401' coro=<handle() done, defined at accesser\__init__.py:93> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>>
2023-05-18 16:06:42 ERROR    asyncio: Task exception was never retrieved
future: <Task finished name='Task-405' coro=<handle() done, defined at accesser\__init__.py:93> exception=SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)')>
Traceback (most recent call last):
  File "accesser\__init__.py", line 129, in handle
  File "asyncio\streams.py", line 48, in open_connection
  File "asyncio\base_events.py", line 1112, in create_connection
  File "asyncio\base_events.py", line 1145, in _create_connection_transport
  File "asyncio\sslproto.py", line 574, in _on_handshake_complete
  File "asyncio\sslproto.py", line 556, in _do_handshake
  File "ssl.py", line 979, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)
2023-05-18 16:06:42 ERROR    asyncio: Task exception was never retrieved
future: <Task finished name='Task-412' coro=<handle() done, defined at accesser\__init__.py:93> exception=SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)')>

**Comment by URenko** [comment]
已于 [v0.8.2](https://github.com/URenko/Accesser/releases/tag/v0.8.2) 适配
