### ISSUE TITLE
访问pornhub出错

### ISSUE THREAD

**Issue by aehope** [URenko/Accesser#150]
我是纯小白
ConnectionResetError: [WinError 64] 指定的网络名不再可用。
2023-10-24 12:52:30 DEBUG    Accesser: 127.0.0.1:59461 say: CONNECT pornhub.com:443 HTTP/1.1
2023-10-24 12:52:30 DEBUG    Accesser: [59461] DNS: pornhub.com -> 66.254.114.41
2023-10-24 12:52:30 DEBUG    Accesser: 127.0.0.1:59462 say: CONNECT pornhub.com:443 HTTP/1.1
2023-10-24 12:52:30 DEBUG    Accesser: [59462] DNS: pornhub.com -> 66.254.114.41
2023-10-24 12:52:30 DEBUG    Accesser: [59461] server_hostname=''
2023-10-24 12:52:30 DEBUG    Accesser: [59462] server_hostname=''
2023-10-24 12:52:32 ERROR    asyncio: Task exception was never retrieved
future: <Task finished name='Task-121' coro=<handle() done, defined at D:\Accesser\Accesser-master\accesser\__init__.py:94> exception=ConnectionRefusedError(22, '远程计算机拒绝网络连接。', None, 1225, None)>
Traceback (most recent call last):
  File "D:\Accesser\Accesser-master\accesser\__init__.py", line 131, in handle
    remote_reader, remote_writer = await asyncio.open_connection(remote_ip, port, ssl=remote_context, server_hostname=server_hostname)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1099, in create_connection
    raise exceptions[0]
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1081, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 984, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 727, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 798, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 594, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。
2023-10-24 12:53:02 ERROR    asyncio: Task exception was never retrieved
future: <Task finished name='Task-123' coro=<handle() done, defined at D:\Accesser\Accesser-master\accesser\__init__.py:94> exception=ConnectionRefusedError(22, '远程计算机拒绝网络连接。', None, 1225, None)>
Traceback (most recent call last):
  File "D:\Accesser\Accesser-master\accesser\__init__.py", line 131, in handle
    remote_reader, remote_writer = await asyncio.open_connection(remote_ip, port, ssl=remote_context, server_hostname=server_hostname)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1099, in create_connection
    raise exceptions[0]
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1081, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 984, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 727, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 798, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aehope\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 594, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

**Comment by aehope** [comment]
是pornhub像youtube和twitter那种被墙了吗？而且我注意到pornhub貌似只有一个ip地址

**Comment by Xihihhh** [comment]
可能是Pornhub不能置空SNI访问或拒绝大陆IP(因为[GhosTCP](https://github.com/macronut/ghostcp)似乎也不行)

**Comment by jonm58** [comment]
pornhub.com的IP100%没得用,443已经封死了
100%要得走中转

**Comment by Xihihhh** [comment]
> pornhub.com的IP100%没得用,443已经封死了 100%得走中转

所以你的GhosTCP配置为什么还保留着

**Comment by aehope** [comment]
> pornhub.com的IP100%没得用,443已经封死了 100%得走中转

感谢您的回答！我已知晓。但我又遇到几个问题，请问您可以帮我解决吗？很抱歉，我对代码之类并不是很了解。只能麻烦您。
1.我试图使用wiki里的办法来在安卓上运行此文件，成功运行。但是手机添加信任ca证书后，浏览器访问网页仍然显示为不安全的网站，个人能力有限，不知道该如何解决，抱歉。
2.我想修改pac文件来添加可访问的网址，但我并不熟悉termux的操作方式，甚至找不到pac文件，请问该怎么办？termux能正常使用。

**Comment by jonm58** [comment]
> > pornhub.com的IP100%没得用,443已经封死了 100%得走中转
> 
> 感谢您的回答！我已知晓。但我又遇到几个问题，请问您可以帮我解决吗？很抱歉，我对代码之类并不是很了解。只能麻烦您。 1.我试图使用wiki里的办法来在安卓上运行此文件，成功运行。但是手机添加信任ca证书后，浏览器访问网页仍然显示为不安全的网站，个人能力有限，不知道该如何解决，抱歉。 2.我想修改pac文件来添加可访问的网址，但我并不熟悉termux的操作方式，甚至找不到pac文件，请问该怎么办？termux能正常使用。

 - 1.最好用FireFox,其他App可能不使用导入的证,书
 - 2.在Github下载这pac到工作目录,再自己修改

**Comment by Xihihhh** [comment]
> > pornhub.com的IP100%没得用,443已经封死了 100%得走中转
> 
> 感谢您的回答！我已知晓。但我又遇到几个问题，请问您可以帮我解决吗？很抱歉，我对代码之类并不是很了解。只能麻烦您。 1.我试图使用wiki里的办法来在安卓上运行此文件，成功运行。但是手机添加信任ca证书后，浏览器访问网页仍然显示为不安全的网站，个人能力有限，不知道该如何解决，抱歉。 2.我想修改pac文件来添加可访问的网址，但我并不熟悉termux的操作方式，甚至找不到pac文件，请问该怎么办？termux能正常使用。

termux 文件修改可以用 nano，适合小白

**Comment by UjuiUjuMandan** [comment]
> 最好用FireFox,其他App可能不使用导入的证书

Chrome 使用啊，它会接受在系统安装的用户证书，比 FF 需要手动导入一次方便多了。
