### ISSUE TITLE
AttributeError: module 'cryptography.hazmat.primitives.serialization' has no attribute 'pkcs12'

### ISSUE THREAD

**Issue by Xihihhh** [URenko/Accesser#160]
新的[自动构建](https://github.com/URenko/Accesser/actions/runs/8037922109)程序报错
```
Traceback (most recent call last):
  File "accesser\__main__.py", line 7, in <module>
  File "accesser\__init__.py", line 227, in run
  File "asyncio\runners.py", line 194, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 685, in run_until_complete
  File "accesser\__init__.py", line 215, in main
  File "accesser\utils\importca.py", line 104, in import_ca
  File "accesser\utils\importca.py", line 62, in import_windows_ca
AttributeError: module 'cryptography.hazmat.primitives.serialization' has no attribute 'pkcs12'
[14176] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by URenko** [comment]
应该是最近 pyinstaller 的更新揭露了这一导入错误
