### ISSUE TITLE
每过一段时间需要重启才能正常运行

### ISSUE THREAD

**Issue by bluesky-dark** [URenko/Accesser#17]
使用SwitchyOmega切换
启动一段时间后访问wiki，pixiv会提示响应时间过长或意外终止了连接
日志
`HTTP/1.1
2019-03-16 21:21:10 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-16 21:21:10 DEBUG    L103 GET /rpc/notify_count.php?op=count_unread HTTP/1.1
2019-03-16 21:21:19 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-16 21:21:19 DEBUG    L103 GET /OneSignalSDKWorker.js?appId=b2af994d-2a00-40ba-b1fa-684491f6760a HTTP/1.1
2019-03-17 08:51:04 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 08:51:05 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 08:51:05 DEBUG    L103 GET /zh-hans/MD5 HTTP/1.1
2019-03-17 08:51:06 DEBUG    L103 GET /w/load.php?lang=zh-hans&modules=ext.3d.styles%7Cext.cite.styles%7Cext.math.styles%7Cext.pygments%2CwikimediaBadges%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.toc.styles%7Cskins.vector.styles%7Cwikibase.client.init&only=styles&skin=vector HTTP/1.1
2019-03-17 08:51:06 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 08:51:06 DEBUG    L103 GET /w/load.php?lang=zh-hans&modules=startup&only=scripts&skin=vector HTTP/1.1
2019-03-17 08:51:06 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 08:51:06 DEBUG    L103 GET /w/load.php?lang=zh-hans&modules=ext.gadget.hideConversionTab%2Clarge-font&only=styles&skin=vector HTTP/1.1
2019-03-17 08:52:25 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 08:52:25 DEBUG    L103 GET /api/rest_v1/page/summary/%E4%B8%AD%E5%9C%8B%E7%A7%91%E5%AD%B8%E9%99%A2 HTTP/1.1
2019-03-17 09:52:33 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:33 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:33 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:34 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:34 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:34 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:37 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:37 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:37 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:42 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:42 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:42 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:54 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:54 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:52:54 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:00 WARNING  L2162 404 GET /favicon.ico (127.0.0.1) 1.99ms
2019-03-17 09:53:01 ERROR    L1670 Uncaught exception GET /configfile (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:7654', method='GET', uri='/configfile', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\7zS03A0B4BA\python\tornado\web.py", line 1590, in _execute
  File "C:\Users\user\AppData\Local\Temp\7zS03A0B4BA\utils\webui.py", line 28, in get
FileNotFoundError: [WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£: 'C:\\Users\\user\\AppData\\Local\\Temp\\7zS03A0B4BA\\setting.ini'
2019-03-17 09:53:01 ERROR    L2162 500 GET /configfile (127.0.0.1) 141.81ms
2019-03-17 09:53:30 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:30 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:30 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:33 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:33 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:33 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:34 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:34 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:34 DEBUG    L103 CONNECT zh.wikipedia.org:443 HTTP/1.1
2019-03-17 09:53:38 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:38 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:38 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:38 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:38 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:38 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:39 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:39 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:43 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:43 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:43 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:43 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:45 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
2019-03-17 09:53:45 DEBUG    L103 CONNECT www.pixiv.net:443 HTTP/1.1
`
（9点以后不能访问）

**Comment by URenko** [comment]
@bluesky-dark 请问问题是否仍存在。可能只是外网连接慢的偶发事件。

**Comment by URenko** [comment]
暂时无法复现问题，若问题再次出现再reopen issue
