### ISSUE TITLE
MacOS正常，切换到Windows出现证书问题

### ISSUE THREAD

**Issue by PYUDNG** [URenko/Accesser#178]
在MacOS Big Sur上正常运行，使用pip安装+Clash Meta配合使用，没有问题；
近期切换到windows，`windows11`+`python3.12`+pip安装后，使用命令`accesser`运行，运行出现错误：

<details>
Microsoft Windows [版本 10.0.22631.3527]
(c) Microsoft Corporation。保留所有权利。

D:\Software\Accesser>accesser
Accesser v0.9.4  Copyright (C) 2018-2024  URenko
Serving on ('127.0.0.1', 7654)
2024-07-28 15:47:37 WARNING  Accesser: Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Python312\Lib\http\client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python312\Lib\http\client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python312\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python312\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "C:\Program Files\Python312\Lib\http\client.py", line 1035, in send
    self.connect()
  File "C:\Program Files\Python312\Lib\http\client.py", line 1477, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Program Files\Python312\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\InvFish\AppData\Roaming\Python\Python312\site-packages\accesser\__init__.py", line 190, in update_checker
    with request.urlopen(pypi_url) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
</details>

已经尝试过FAQ，包括但不限于以下方法：
- 在certmgr.msc中手动删除Accesser证书后，使用命令行导入root.pfx
- 在certmgr.msc中手动删除Accesser证书后，修改配置文件使`importca = false`，再使用命令行导入root.pfx
- 在certmgr.msc中手动删除Accesser证书后，修改配置文件使`importca = true`，运行accesser
- 使用这个![截屏2024-07-28 下午3 54 02](https://github.com/user-attachments/assets/5be98eed-c877-4398-bc46-bfa5b6cc3980)一键程序
- 双击root.pfx手动导入证书到**受信任的根证书颁发机构**里

无果，来求助

**Comment by PYUDNG** [comment]
不知道为什么现在又可以了…好像问题自己消失了。在此期间我卸载了一些软件（联想应用商店，联想浏览器等），也没有其他操作。issue我先close掉了，如遇问题再反馈。
