### ISSUE TITLE
在termux上使用时……DNS超时？

### ISSUE THREAD

**Issue by dzx-dzx** [URenko/Accesser#47]
- 
~~~
Exception happened during processing of request from ('127.0.0.1', 34712)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "accesser.py", line 193, in handle
    if not self.parse_host():
  File "accesser.py", line 109, in parse_host
    self.remote_ip = DNSquery(host)
  File "accesser.py", line 260, in DNSquery
    return DNSresolver.query(domain, 'A')[0].to_text()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/dns/resolver.py", line 992, in query
    timeout = self._compute_timeout(start, lifetime)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/dns/resolver.py", line 799, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.004198789596558 seconds
~~~

**Comment by URenko** [comment]
dnscrypt-proxy是否放入dnscrypt目录？

**Comment by dzx-dzx** [comment]
@URenko 是。

**Comment by URenko** [comment]
可以检查下dnscrypt-proxy的进程是否存在，还有53000端口（默认）的占用情况。

如果这些都没问题可以检查下`dnscrypt/dnscrypt-proxy.log`的内容。

**Comment by dzx-dzx** [comment]
@URenko 进程存在，端口也没占用，但是似乎log文件根本没生成。

**Comment by dzx-dzx** [comment]
对不起……那个文件我下成了32位……
不过虽然wiki可以用了，本来正常的网站（baidu，bing）好像打不开了？

**Comment by URenko** [comment]
> 不过虽然wiki可以用了，本来正常的网站（baidu，bing）好像打不开了？

系统代理用的是PAC模式吗

**Comment by dzx-dzx** [comment]
我不太确定……我是从系统的WiFi界面设置的。

**Comment by URenko** [comment]
你填写了什么，比如`127.0.0.1:7655`或`http://127.0.0.1:7654/pac/`

**Comment by dzx-dzx** [comment]
http://127.0.0.1:7654/pac/

**Comment by URenko** [comment]
这个有点奇怪，按道理就算百度从Accesser走也不会出问题，换个浏览器试试，也许不同浏览器对PAC的处理不同?

**Comment by dzx-dzx** [comment]
我用了百度app（…）似乎也不行。

**Comment by URenko** [comment]
> 我用了百度app（…）似乎也不行。
> 或者QQ内置的webview。

不要用App，他们可能不使用导入的证书

**Comment by dzx-dzx** [comment]
啊，chrome是可以的。

**Comment by URenko** [comment]
Firefox参考 https://github.com/URenko/Accesser/wiki/Firefox设置方法 和 #18  
App大多数都不行

**Comment by dzx-dzx** [comment]
我想我在Firefox是点过导入证书的……
