### ISSUE TITLE
ERROR: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by WilliamGong** [URenko/Accesser#61]
在Windows上不能运行exe，所以我就手动安装了。然后运行accesser.py时就报了上述错误。
而且访问127.0.0.1:7654/pac报404，貌似手动安装不能自动配置pac，需要手动配置吗
日志：
2019-10-13 12:06:44 INFO     Accesser: server started at 127.0.0.1:7655
2019-10-13 12:06:44 ERROR    Accesser: [WinError 2] 系统找不到指定的文件。

**Comment by URenko** [comment]
https://github.com/URenko/Accesser/blob/fdd28750f123328bb276ac3d3bb2a16c409d3d62/utils/log.py#L17
你把`utils/log.py`里的
`%(asctime)s %(levelname)-8s %(name)s: %(message)s`
改成
`%(asctime)s %(levelname)-8s %(name)s[%(lineno)d]: %(message)s`
看看具体出错的地方

**Comment by WilliamGong** [comment]
log：

2019-10-20 10:54:40 ERROR    tornado.access[2246]: 500 GET /pac/ (127.0.0.1) 2.00ms
2019-10-20 10:54:55 ERROR    tornado.application[1788]: Uncaught exception GET /pac/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:7654', method='GET', uri='/pac/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "C:\Users\gtl11\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tornado\web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Users\gtl11\Accesser\utils\webui.py", line 73, in get
    with open('pac') as f:
PermissionError: [Errno 13] Permission denied: 'pac'

**PermissionError: [Errno 13] Permission denied: 'pac'**

我fo了

**Comment by URenko** [comment]
有些奇怪，放到其他地方试试，另外工作目录应该是在Accesser目录吧

**Comment by WilliamGong** [comment]
没错，目录下运行，普通用户权限

**Comment by WilliamGong** [comment]
emmm，估计是mingw的python2与我自己的python3冲突，mingw删掉后就好了
