### ISSUE TITLE
windows10无法使用py

### ISSUE THREAD

**Issue by LCinHK** [URenko/Accesser#72]
2020-01-15 16:26:38 ERROR    Accesser[100]: 
2020-01-15 16:26:39 INFO     Accesser[242]: server started at 127.0.0.1:7655
2020-01-15 16:26:39 ERROR    Accesser[247]: [WinError 2] The system cannot find the file specified
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\urllib\request.py", line 1317, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Program Files\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Program Files\Python38\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Program Files\Python38\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\Python38\lib\socket.py", line 807, in create_connection
    raise err
  File "C:\Program Files\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Accesser\accesser.py", line 263, in update_checker
    with request.urlopen('https://github.com/URenko/Accesser/releases/latest') as f:
  File "C:\Program Files\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 1360, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Python38\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

求助！此外localhost:7654打开空白

**Comment by URenko** [comment]
看起来似乎是
1. sysproxy.exe未放置
2. github访问慢（检查更新）

**Comment by LCinHK** [comment]
就是github问题，谢谢了。
也因此，安卓至今用不了
